steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/cx-login:$COMMIT_SHA',
        '-f',
        'cx-login/Dockerfile',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/cx-login:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
